from enum import Enum

class Felina(Enum):
    ABISSINIO = 1
    EXOTICO = 2
    HIMALAIO = 3
    LAPERM_ = 4
    MAINE_COON = 5
    MUNCHKIN = 6
    ORIENTAL_HAVANA = 7
    ORIENTAL_LILAC_TABBY_SPOTTED = 8
    ORIENTAL_PRETO = 9
    ORIENTAL_SHORTHAIR = 10
    PELO_CURTO_BRASILEIRO_ = 11
    AMERICAN_CURL = 12
    PERSA = 13
    PIXIE_BOB = 14
    RAGDOLL = 15
    SAGRADO_DA_BIRMANIA_ = 16
    SCOTTISH_FOLD = 17
    SIAMES = 18
    SOMALI = 19
    SPHYNX = 20
    SRD = 21
    TURKISH_VAN = 22
    AMERICAN_SHORTHAIR = 23
    EGYPTIAN_MAU = 24
    BALINES = 25
    BENGAL = 26
    BOBTAIL_JANOPES_ = 27
    BRITISH_CREME = 28
    BRITISH_SHOTHAIR = 29
    EUROPEU_PRETO = 30
